package com.bn.common.dto.common;

/**
 * Different types of license encryption for DRM licenses.  All DRM licenses require user encryption around the book key. BN supports multiple types of user encryption
 *
 * User: ataylor
 * Date: 4/10/12
 * Time: 7:51 PM
 */
public enum LicenseEncryptionType {
    INVALID,
    PDB_CCHASH,             //Generated by EDS C++ component, used for Fictionwise ereader clients & pdb file types
    CCHASH,                 //Generated by EDS.NET C# component (wrapped by Calibern), used for Adobe RMSDK ereader epubs
    USER_SYM_KEY,           //Generated by BnCloud, used for Adobe RMSDK ereader and NERE ereader epubs
    USER_PRIVATE_KEY,       //For future use, will be generated by BnCloud
    DEVICE_KEY,             //Generated during device manufacture, stored in BnCloud/EDM, not yet in use for license encryption
    ;


    public static LicenseEncryptionType getType(int value){
        if(value < 0 || value >= LicenseEncryptionType.values().length){
            return LicenseEncryptionType.INVALID;
        }
        return LicenseEncryptionType.values()[value] ;
    }
}
