openapi: 3.0.0
info:
  title: Device API
  version: 1.0.0
servers:
  - url: 'https://nook-apim-dev-eastus.azure-api.net'
paths:
  /device/createAccountProfile:
    post:
      summary: API for Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountProfileRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountProfileResponse'
        'default':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Response status
                  code:
                    type: string
                    description: Error code
                  message:
                    type: string
                    description: Response message
components:
  schemas:
    CreateAccountProfileRequest:
      type: object
      properties:
        profileType:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - profileType
        - firstName
        - lastName
    SyncItem:
      type: object
      properties:
        luid:
          type: string
        guid:
          type: string
        modTime:
          type: string
        data:
          type: string
        categoryType:
          type: string
        action:
          type: string
        profileId:
          type: string
    CreateAccountProfileResponse:
      type: object
      properties:
        resultCode:
          type: string
        syncItem:
          $ref: '#/components/schemas/SyncItem'
      required:
        - resultCode
        - syncItem
