openapi: 3.0.0
info:
  title: Device API
  version: 1.0.0
servers:
  - url: https://nook-apim-dev-eastus.azure-api.net
paths:
  /device/getPassPhrase:
    post:
      summary: 'API for getting a secret passphrase'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetPassPhraseRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPassPhraseResponse'
        'default':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Response status
                  code:
                    type: string
                    description: Error code
                  message:
                    type: string
                    description: Response message

components:
  schemas:
    GetPassPhraseRequest:
      type: object
      properties:
        uniqueId:
          type: string
          description: Device Serial number
        modelId:
          type: string
          description: Device Model Id
      required:
        - uniqueId
        - modelId
    GetPassPhraseResponse:
      type: object
      properties:
        passphrase:
          type: string
          description: secret passphrase
        notifications:
          type: array
          items:
            $ref: '#/components/schemas/Notifications'
          nullable: true
          description: List of notifications (if any)
        messageid:
          type: string
          description: unique transaction ID
    Notifications:
      type: object
      properties:
        category:
          type: integer
          enum: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
          description: |
            0 - SW
            1 - SYNC
            2 - CCH
            3 - ABC
            4 - REFCR
            5 - SQFR
            6 - SYNC_TIME
            7 - SYNC_RP
            8 - SYNC_BO
            9 - SYNC_AN
            10 - SYNC_LO
            11 - LRFR
            12 - LIST
            13 - SYSTEM_SOFTWARE
            14 - SYNC_DC
            15 - SYNC_DC_TIME
            16 - PROVISION
            17 - ENTITLEMENT
            18 - USERPROFILES
            19 - PARTNER_AUTH
            20 - PARTNER_DEAUTH
            21 - SYNC_VL
            22 - SYNC_VE
            23 - ACCOUNT_LINK
            24 - PURCHASE_BLOCK
            25 - PURCHASE_ALLOW
        time:
          type: string
          format: date-time
        desc:
          type: string
          description: the description about the notification.
          nullable: true
        transient:
          type: boolean
          nullable: true
